- Encode each of the 10 scores in a vector of 10 elements, with all elements set to 0 but one, at a different index for each score. 
- This way, a score of 1 could be mapped onto the vector
(1,0,0,0,0,0,0,0,0,0), a score of 5 onto (0,0,0,0,1,0,0,0,0,0), and so on.
-  Note that the fact that the score corresponds to the index of the nonzero element is purely incidental.

In [11]:
import torch
import numpy as np

In [12]:
wine_path = 'winequality-white.csv'
wineq_numpy = np.loadtxt(wine_path, dtype = np.float32, delimiter=";", skiprows= 1)
wineq = torch.from_numpy(wineq_numpy)
wineq, wineq.shape

(tensor([[ 7.0000,  0.2700,  0.3600,  ...,  0.4500,  8.8000,  6.0000],
         [ 6.3000,  0.3000,  0.3400,  ...,  0.4900,  9.5000,  6.0000],
         [ 8.1000,  0.2800,  0.4000,  ...,  0.4400, 10.1000,  6.0000],
         ...,
         [ 6.5000,  0.2400,  0.1900,  ...,  0.4600,  9.4000,  6.0000],
         [ 5.5000,  0.2900,  0.3000,  ...,  0.3800, 12.8000,  7.0000],
         [ 6.0000,  0.2100,  0.3800,  ...,  0.3200, 11.8000,  6.0000]]),
 torch.Size([4898, 12]))

In [13]:
target = wineq[:, -1]
target, target.shape

(tensor([6., 6., 6.,  ..., 6., 7., 6.]), torch.Size([4898]))

In [15]:
target_onehot = torch.zeros(target.shape[0], 10) # 4894 x 10 shape
target_onehot.scatter_(1, target.unsqueeze(1).long(), 1.0)
# scatter_ = inplace scatter, no new tensor is created
# 1 = scatter 1.0 among the rows. If 0 then along columns 
# .unsqueeze(1) = adds a dimension of column
# .long() = typecast to labels or convert to int64
# 1.0 = value to be scatterred

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 1., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [19]:
target.unsqueeze(1), target.unsqueeze(0), target.unsqueeze(1).long()

(tensor([[6.],
         [6.],
         [6.],
         ...,
         [6.],
         [7.],
         [6.]]),
 tensor([[6., 6., 6.,  ..., 6., 7., 6.]]),
 tensor([[6],
         [6],
         [6],
         ...,
         [6],
         [7],
         [6]]))

In [20]:
bad_indexes = target <= 3
bad_indexes.shape, bad_indexes.dtype, bad_indexes.sum()

(torch.Size([4898]), torch.bool, tensor(20))