In [15]:
import torch

In [16]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [17]:
a[1]

tensor(1.)

In [18]:
float(a[1])

1.0

In [19]:
a[2]=2.0
a

tensor([1., 1., 2.])

In [20]:
points = torch.tensor([[4,4,1],[3,2,1]])
points

tensor([[4, 4, 1],
        [3, 2, 1]])

In [21]:
points[1,1]

tensor(2)

In [22]:
points.shape

torch.Size([2, 3])

In [23]:
points2 = torch.zeros(3,2)
points2

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
points[1:2]

tensor([[3, 2, 1]])