Some tensor operations in PyTorch only work on contiguous tensors, such as view

In [1]:
import torch

In [2]:
points = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
points_t = points.t() # transposing without copying. here stride is changed internally

In [9]:
print("In Storage:\n", points.storage(), "\n")
print(points)
print("Contiguous: ", points.is_contiguous(), "\n")
print(points_t)
print("Contiguous: ", points_t.is_contiguous())

In Storage:
  1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6] 

tensor([[1., 2., 3.],
        [4., 5., 6.]])
Contiguous:  True 

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
Contiguous:  False


In [10]:
points_t.storage()

 1.0
 2.0
 3.0
 4.0
 5.0
 6.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [11]:
points_t.stride()

(1, 3)

In [12]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [13]:
points_t_cont.storage()
# here the storage is reshuffled to accomodate contiguous storage

 1.0
 4.0
 2.0
 5.0
 3.0
 6.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [14]:
points_t_cont.stride()

(2, 1)